### ISSUE TITLE
PutNT Module Breaks Pipeline When "None" is passed to it

### ISSUE THREAD

**Issue by thecodeweaver** [opensight-cv/opensight#29]
When using the PutNT module, the pipeline fails to "compile" (the status indicator becomes a red X) if the PutNT module does not immediately receive an input that is not "None".

**Comment by dzil123** [comment]
Are you using the latest version v0.2.2?
Could you please post a screenshot of your pipeline, as well as the full error message?
You can find logs at http://opensight.local:5800/logs

**Comment by thecodeweaver** [comment]
I am not using the latest release. I'm going to see if this is still a problem in version v0.2.2.
Here is my pipeline: 
<img width="829" alt="Pipeline" src="https://user-images.githubusercontent.com/44348986/74070597-552b5480-49b6-11ea-8ba7-1b8fe051408f.png">

Here is the full error message:
![image](https://user-images.githubusercontent.com/44348986/74071012-750f4800-49b7-11ea-8a1c-258e70b3dd77.png)

**Comment by 132ikl** [comment]
This has been fixed in version v0.2.4.
